routebeat:
  period: 30s
  tags:
    - "MES"
    - "IPAN"
  api:
    url: "https://129.153.131.121/graphql/v1.1"
    notifications: true
    limit: 2000    
    auth:
      client_id: "insite-poller"
      client_secret: "QdS1US0v2xABh4d5CliQAWZrmSGPMOxd"
      token_url: "https://129.153.131.121/auth/realms/magnum/protocol/openid-connect/token"
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
