input {
   beats {
      id    => "ROUTETEST-INPUT"
      port  => 5057
      tags  => [ "data-routetest" ]
   }
}

output {
   elasticsearch {
      id                 => "ROUTETEST-ELASTIC"
      index              => "log-routetest-%{+YYYY.MM.dd}"
      hosts              => [ "N1.node.evertz:9200" ]
      template           => "/opt/mappings/elasticsearch-template-routetest.json"
      template_name      => "log-routetest"
      template_overwrite => true
      action             => "create"
   }

   pipeline {
     id => "RABBIT-FORWARDER"
     send_to => "rabbitmq"
     ensure_delivery => false
   }
}